category = ['motoryzacja', 'nieruchomosci', 'dom-ogrod', 'elektronika', 'moda', 'rolnictwo', 'zwierzeta', 'dla-dzieci',
            'slub-i-wesele', 'muzyka-edukacja', 'sport-hobby']

category_dict = {'motoryzacja': 'Авто', 'nieruchomosci': 'Недвижимость', 'dom-ogrod': 'Дом-сад',
                 'elektronika': 'Электроника', 'moda': 'Одежда', 'rolnictwo': 'Сх', 'zwierzeta': 'животные',
                 'dla-dzieci': 'Дети',
                 'slub-i-wesele': 'Свадьба', 'muzyka-edukacja': 'Музыка', 'sport-hobby': 'Спорт'}

subcategory = {
    'motoryzacja': {'samochody': 'Легковые', 'czesci-samochodowe': 'Запчасти', 'pozostala-motoryzacja': 'Другие авто',
                    'motocykle-skutery': 'Мотоциклы-скутеры',
                    'czesci-motocyklowe': 'Мото запчасти', 'dostawcze-ciezarowe': 'Грузовики',
                    'opony-felgi': 'Шины и диски',
                    'przyczepy-pojazdy-uzytkowe': 'Прицепы', 'car-audio': 'Звук'},
    'nieruchomosci': {'stancje-pokoje': 'Снять хату?', 'biura-lokale': 'Офисы', 'noclegi': 'Ночлег?',
                      'dzialki': 'Земля',
                      'pozostale-nieruchomosci': 'Другое', 'kwatery-pracownicze': 'Служебные', 'domy': 'Дома',
                      'hale-magazyny': 'Склады',
                      'garaze-parkingi': 'Гараж', 'mieszkania': 'Квартиры'},
    'dom-ogrod': {'meble': 'Мебель', 'materialy-budowlane': 'Строймат', 'sprzet-agd': 'Техника', 'zdrowie': 'Здоровье',
                  'ogrzewanie': 'Обогрев',
                  'ogrod': 'Сад', 'wyposazenie-wnetrz': 'Интерьер', 'narzedzia': 'Инструменты',
                  'ozostale-dom-ogrod': 'Другое', },
    'elektronika': {'telefony-komorkowe': 'Телефоны', 'tablety': 'Планшеты', 'fotografia': 'Фото',
                    'akcesoria-telefoniczne': 'Аксессуары',
                    'telewizory': '', 'mp3-sprzet-audio': '', 'komputery': '', 'gry-konsole': '',
                    'pozostala-elektronika': 'Другое', 'sprzet-agd': 'Бытовая техника',
                    'sprzet-dvd-blu-ray': 'dvd-blur ray', },
    'moda': {'ubrania': 'Одежда', 'dodatki': 'Добавки?', 'kosmetyki-perfumy': 'Косметика', 'buty': 'Сапоги',
             'bizuteria': 'Бижутерия', 'pozostala-moda': 'отдых?',
             'bielizna': 'Нижнее болье', 'torebki': 'Сумки', 'odziez-ciazowa': 'Для залетных', 'zegarki': 'Часы'},
    'rolnictwo': {'ciagniki': 'Тракторы', 'opony-rolnicze': 'Шины', 'pozostale-rolnicze': 'Другое',
                  'maszyny-rolnicze': 'Сх техника',
                  'produkty-rolne': 'Сх продукты?', 'przyczepy': 'Трейлеры', 'gielda-zwierzat': 'Животные',
                  'czesci-do-maszyn-rolniczych': 'Запчасти',
                  'ryneczek': 'Рынок'},
    'zwierzeta': {'psy': 'Собаки', 'konie': 'Кони', 'akwarystyka': 'Рыбы', 'koty': 'Коты', 'ptaki': 'Птицы',
                  'pozostale-zwierzeta': 'Другое', 'gryzonie': 'Грызуны', 'akcesoria-dla-zwierzat': 'Аксессуары'},
    'dla-dzieci': {'zabawki': 'Игрушки', 'ubranka-dla-dzieci': 'Одежда ', 'wozki-dzieciece': 'Коляски',
                   'buciki': 'Обувь',
                   'akcesoria-dla-niemowlat': 'Аксуссуары', 'meble-dla-dzieci': 'Мебель',
                   'foteliki-nosidelka': 'Кресла',
                   'pozostale-dla-dzieci': 'Другое', },
    'slub-i-wesele': {'moda-slubna': 'Одежда', 'akcesoria-slubne': 'Аксуссууары'},
    'muzyka-edukacja': {'ksiazki': 'Книги', 'sprzet-muzyczny': 'Муз. оборуд.', 'muzyka': 'Музыка',
                        'pozostala-muzyka-edukacja': 'Другое',
                        'filmy': 'Фильмы', 'materialy-jezykowe': 'Языковые материалы', 'instrumenty': 'Инструменты'},
    'sport-hobby': {'bilety': 'Билеты', 'fitness': 'Фитнес', 'spolecznosc': 'Сообщество',
                    'pozostaly-sport-hobby': 'Другое', 'Коллекции': '',
                    'sporty-zimowe': 'Зимний спорт', 'sporty-wodne': 'Водный сопрт',
                    'akcesoria-jezdzieckie': 'Аксессуары для коня', 'militaria': 'Военка',
                    'wedkarstwo': '', 'odziez-sportowa': '', 'skating': '', 'rowery': '', 'turystyka': '',
                    'obuwie-sportowe': 'Обувь'}}
